name: Bug report
description: 报告一个问题或缺陷，帮助我们改进插件
title: "bug: "
labels: [bug]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢提交 Bug！请尽可能提供详细信息，便于定位和修复。

  - type: input
    id: version
    attributes:
      label: 插件版本
      description: 例如 v3.6（或 manifest.json 中的 version）
      placeholder: v3.6
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 清晰描述出现了什么问题，以及预期行为是什么
      placeholder: 具体报错、异常现象、影响范围……
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 按步骤描述如何复现问题
      placeholder: |
        1. 打开扩展
        2. 点击 xxx
        3. 出现错误信息……
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: 操作系统与浏览器版本
      description: 例如 Windows 11 / Chrome 129
      placeholder: Windows 11 / Chrome 129

  - type: textarea
    id: logs
    attributes:
      label: 控制台日志或截图
      description: 如有报错信息或截图，请粘贴或上传

  - type: checkboxes
    id: checks
    attributes:
      label: 提交前检查
      options:
        - label: 已搜索现有 Issue，确认未重复
          required: true
        - label: 已在最新版本复测
          required: true