name: Feature request
description: 提出一个新功能或改进建议
title: "feat: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请尽可能提供清晰的动机与场景。

  - type: textarea
    id: motivation
    attributes:
      label: 背景与动机
      description: 为什么需要这个功能？解决什么问题？
      placeholder: 业务场景、使用痛点、目标效果……
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 功能提案
      description: 简述你期望的实现方式或交互流程
      placeholder: 例如在 popup 增加一个按钮，点击后执行……
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 备选方案或权衡
      description: 是否有其他思路？各自优缺点是什么？

  - type: input
    id: screenshots
    attributes:
      label: 相关截图或草图链接
      description: 可选，便于理解需求与设计

  - type: checkboxes
    id: impact
    attributes:
      label: 影响范围（勾选所有适用项）
      options:
        - label: UI/交互变更
        - label: 配置与存储
        - label: 网络请求或权限
        - label: 兼容性与性能